#!/bin/bash
#
# bcm5943-post-install - post-installing the BCM5974
#
# Copyright (C) 2008	   Henrik Rydberg (rydberg@euromail.se)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

DRIVER=bcm5974
ETCPATH=/etc/modprobe.d/$DRIVER

echo -----------------------------------------------------------------------

DIR=`dirname $0`
LSUSB=/usr/sbin/lsusb

PAT_HEAD="options usbhid quirks="
PAT[0]="05ac:022"
PAT[1]="05ac:023"
MATCH[0]=${PAT_HEAD}0x05ac:0x022
MATCH[1]=${PAT_HEAD}0x05ac:0x023

if [ -x $LSUSB ]; then
    if [ "`$LSUSB|grep ${PAT[0]}`" != "" ]; then
        SED="s/#${MATCH[0]}/${MATCH[0]}/"
    elif [ "`$LSUSB|grep ${PAT[1]}`" != "" ]; then
        SED="s/#${MATCH[1]}/${MATCH[1]}/"
    else
        echo No suitable device found
        exit 1
    fi
else
    echo \* USB device: UNKNOWN - lsusb not found
    exit 1
fi

cat $DIR/..$ETCPATH | sed "$SED" > $ETCPATH

exit 0
