#!/bin/bash
#
# bcm5943-pre-install - check system before installing the bcm5974
#
# Copyright (C) 2008	   Henrik Rydberg (rydberg@euromail.se)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

DRIVER=bcm5974
LSUSB=/usr/sbin/lsusb

PAT[0]="05ac:022"
PAT[1]="05ac:023"

if [ -x $LSUSB ]; then
    if [ "`$LSUSB|grep ${PAT[0]}`" != "" ]; then
        exit 0
    elif [ "`$LSUSB|grep ${PAT[1]}`" != "" ]; then
        exit 0
    else
        echo bcm5974: no suitable device found
        exit -1
    fi
else
    echo bcm5974: cannot determine device type
    exit -1
fi

exit 0
