#!/bin/bash
#
# bcm5943-post-install - post-installing the BCM5974
#
# Copyright (C) 2008	   Henrik Rydberg (rydberg@euromail.se)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

DRIVER=bcm5974
ETCPATH=/etc/modprobe.d/$DRIVER

echo -----------------------------------------------------------------------

DIR=`dirname $0`
LSUSB=/usr/sbin/lsusb

PAT_HEAD="options usbhid quirks="

DEV[0]="0223"
DEV[1]="0224"
DEV[2]="0225"
DEV[3]="0230"
DEV[4]="0231"
DEV[5]="0232"
DEV[6]="0236"
DEV[7]="0237"
DEV[8]="0238"

if [ -x $LSUSB ]; then
    typeset -i i=0
    while [ $i -lt 9 ]; do
        PAT=05ac:${DEV[$i]}
        MATCH=${PAT_HEAD}0x05ac:0x${DEV[$i]}
        if [ "`$LSUSB|grep $PAT`" != "" ]; then
            SED="s/#$MATCH/$MATCH/"
        fi
        i=$i+1
    done
else
    echo \* USB device: UNKNOWN - lsusb not found
    exit 1
fi

if [ "$SED" != "" ]; then
    cat $DIR/..$ETCPATH | sed "$SED" > $ETCPATH
    exit 0
else
    echo No suitable device found
    exit 1
fi
